on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: rlespinasse/github-slug-action@v4
      with:
        prefix: SLUG_
        slug-maxlength: 'nolimit'
    - run: echo "DOCKER_IMAGE_FQDN=$(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SLUG_GITHUB_REF_NAME }})" >> $GITHUB_ENV

    - name: docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: docker build & push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ env.DOCKER_IMAGE_FQDN }}
        push: true